---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%"
)
options(scipen = 999)

library(forager)
library(dplyr)
library(tidyr)
library(gt)
library(gtExtras)
library(ggplot2)
library(scales)
library(headliner)
```

## Introduction

The `forager` package is a collection of functions that are useful for healthcare revenue cycle analysis. 

## Days in Accounts Receivable

```{r}
dar_ex()
```



```{r}
dar_mon <- avg_dar(
  df     = dar_ex(),
  date   = date,
  gct    = gross_charges,
  earb   = ending_ar,
  dart   = 35,
  period = "month"
)
```



```{r}
dar_mon |> 
  gt(rowname_col = "mon") |> 
  cols_hide(c(date, 
              nmon, 
              month, 
              nqtr, 
              yqtr, 
              dqtr, 
              year, 
              ymon, 
              myear, 
              nhalf, 
              yhalf, 
              dhalf, 
              ndip,
              ending_ar_target,
              dar_diff,
              ratio_ideal,
              ratio_actual)) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  fmt_currency(columns = c(gross_charges, 
                           ending_ar, 
                           adc, 
                           ending_ar_target, 
                           ending_ar_dec_abs, 
                           earb_gct_diff)) |> 
  fmt_percent(columns = c(ending_ar_dec_pct)) |> 
  fmt_number(columns = c(dar, 
                         dar_diff, 
                         ratio_actual, 
                         ratio_ideal, 
                         ratio_diff)) |> 
  cols_move_to_start(c(mon, 
                       gross_charges, 
                       ending_ar, 
                       earb_gct_diff,
                       adc, 
                       dar_pass, 
                       dar, 
                       dar_diff, 
                       ratio_actual, 
                       ratio_ideal, 
                       ratio_diff, 
                       ending_ar_target, 
                       ending_ar_dec_abs, 
                       ending_ar_dec_pct
                       )) |> 
  cols_label(
    mon = "Month",
    gross_charges = "Gross Charges",
    ending_ar = "Ending AR",
    adc = "ADC",
    dar_pass = "",
    dar = "DAR",
    ratio_diff = "AR/GC Diff",
    ending_ar_dec_abs = "AR Decrease Needed",
    ending_ar_dec_pct = "%",
    earb_gct_diff = "AR - GC"
  ) |> 
  opt_stylize()
```


```{r}
dar_mon |> 
  ggplot(aes(x = mon, y = dar)) +
  # geom_point() +
  geom_line(group = 1, linetype = "dashed", alpha = 0.7) +
  geom_hline(yintercept = 35, color = "red") +
  labs(title = "Days in AR by Month", x = NULL, y = NULL) +
  theme_minimal()
```

```{r}
dar_mon |> 
  ggplot(aes(x = ending_ar, y = dar)) +
  geom_point() +
  geom_hline(yintercept = 35, color = "red") +
  scale_x_continuous(labels = dollar_format(prefix = "$"),
                     limits = c(0, dar_mon$ending_ar)) +
  labs(title = "Days in AR by Month", x = NULL, y = NULL) +
  facet_wrap(~month) + 
  coord_flip() +
  theme_minimal()
```



```{r}
dar_ratio <- dar_mon |> 
  select(mon, ratio_ideal)

ggplot(dar_mon, aes(x = gross_charges, y = ending_ar), group = 1) +
  geom_point(alpha = 1) +
  geom_abline(
    slope = dar_ratio$ratio_ideal,
    intercept = 0,
    color = "red") +
  facet_wrap(~month, scales = "free_x") +
  scale_y_continuous(labels = dollar_format(prefix = "$"),
                     limits = c(0, dar_mon$ending_ar)
                     ) +
  scale_x_continuous(labels = dollar_format(prefix = "$"),
                     limits = c(0, dar_mon$gross_charges)) +
  scale_shape_identity() +
  labs(title = NULL, x = "Total Gross Charges", y = "Ending AR Balance") +
  theme(legend.position = "none")
```


```{r}
avg_dar(
  df     = dar_ex(),
  date   = date,
  gct    = gross_charges,
  earb   = ending_ar,
  dart   = 35,
  period = "month"
) |> 
  select(
    month,
    gross_charges,
    ending_ar,
    ending_ar_target,
    dar,
    dar_pass
    ) |> 
  headliner::add_headline_column(
    x = ending_ar, 
    y = ending_ar_target, 
    headline = "{delta_p}% {trend} than Target", 
    trend_phrases = headliner::trend_terms(more = "HIGHER", less = "Lower"), 
    n_decimal = 0) |> 
  gt(rowname_col = "month") |> 
  cols_label(
    gross_charges = "Gross Charges", 
    ending_ar = "Ending AR", 
    ending_ar_target = "Target AR", 
    dar = "Days in AR", 
    dar_pass = "Pass", 
    headline = "Ending AR Trend"
    ) |> 
  tab_row_group(label = "Q4", rows = c(10:12)) |>
  tab_row_group(label = "Q3", rows = c(7:9)) |>
  tab_row_group(label = "Q2", rows = c(4:6)) |>
  tab_row_group(label = "Q1", rows = c(1:3)) |> 
  fmt_number(columns = dar) |>
  fmt_currency(columns = c(gross_charges, ending_ar, ending_ar_target)) |>
  tab_style(style = cell_text(font = c(
    google_font(name = "IBM Plex Mono"),
    default_fonts())), 
    locations = cells_body(columns = c(gross_charges, ending_ar, ending_ar_target, dar))) |> 
  opt_stylize(style = 6, color = "cyan") |> 
  tab_header(
    title = md("Example **Days in AR Analysis** with the **{forager}** Package"), 
    subtitle = md("**May** saw the *highest* Days in AR of 2022 *(51.2)*. This coincided with the largest <br> month-to-month increase in AR & highest percentage over the AR Target *(46%)*.")) |> 
  opt_all_caps() |> 
  grand_summary_rows(
    columns = c(gross_charges, ending_ar, ending_ar_target, dar),
    fns = list(Mean = ~mean(., na.rm = TRUE), Median = ~median(., na.rm = TRUE))) |> 
  opt_table_font(font = list(gt::google_font(name = "Roboto"))) |> 
  opt_align_table_header(align = "left")
```


```{r}
dar_month <- avg_dar(
  df     = dar_ex(),
  date   = date,
  gct    = gross_charges,
  earb   = ending_ar,
  dart   = 35,
  period = "month"
)

# Create df for gt_plt_bar_stack
dar_month_pct <- dar_month |>
  mutate(
    gct_pct = (gross_charges / (gross_charges + ending_ar) * 100),
    earb_pct = (ending_ar / (gross_charges + ending_ar) * 100)) |>
  select(month, gct_pct, earb_pct) |>
  pivot_longer(-month, names_to = "measure", values_to = "percentage") |>
  group_by(month) |>
  summarize(list_data = list(percentage))

# Right join data frames
dar_month_join <- right_join(
  dar_month, 
  dar_month_pct, 
  by = "month")

# Create new copy cols for gt_plt_bullet
dar_month_gt <- dar_month_join |> 
  select(
    month, 
    gross_charges, 
    ending_ar, 
    ending_ar_target,
    dar, 
    dar_pass,
    list_data
    ) |>
  mutate(
    target_col = ending_ar, 
    plot_col = ending_ar_target)

# Create gt table
dar_month_gt |> 
  gt(rowname_col = "month") |>
  cols_label(
    gross_charges = "Gross Charges",
    ending_ar = "Ending AR",
    ending_ar_target = "Optimal AR",
    dar = "Days in AR",
    dar_pass = "Pass",
    plot_col = "Optimal AR Threshold") |>
  tab_row_group(label = "Q4", rows = c(10:12)) |>
  tab_row_group(label = "Q3", rows = c(7:9)) |>
  tab_row_group(label = "Q2", rows = c(4:6)) |>
  tab_row_group(label = "Q1", rows = c(1:3)) |>
  gt_theme_nytimes() |> 
  fmt_number(columns = dar) |>
  fmt_currency(columns = c(gross_charges, ending_ar, ending_ar_target)) |>
  gt_plt_bullet(column = plot_col, 
                target = target_col, 
                palette = c("#8ca0aa", "black"), 
                width = 65
                ) |>
  gt_plt_bar_stack(list_data, 
                   width = 50, 
                   labels = c("Charges (%) ", " AR (%)"), 
                   palette = c("#2c3e50", "#8ca0aa")
                   ) |>
  gt_badge(dar_pass, 
           palette = c("FALSE" = "#8ca0aa")
           ) |> 
  tab_style(style = cell_text(color = "#2c3e50", weight = "bolder"), 
            locations = cells_body(columns = dar_pass, rows = dar_pass == "FALSE")
            ) |>
  tab_style(style = cell_text(color = "#8ca0aa", weight = "normal"), 
            locations = cells_body(columns = dar_pass, rows = dar_pass == "TRUE")
            ) |> 
  data_color(columns = c(gross_charges, ending_ar, dar), 
             colors = col_numeric(palette = c("#2c3e50", "#8ca0aa") |> 
                                    as.character(), 
                                  domain = NULL)
             ) |> 
  tab_footnote(footnote = "Horizontal bar indicates Optimal AR, vertical bar is Actual.", 
               locations = cells_column_labels(columns = plot_col)
               ) |> 
  tab_header(title = md("Example **Days in AR Analysis** with the **{forager}** Package"))
```




```{r}
avg_dar(
  df     = dar_ex(),
  date   = date,
  gct    = gross_charges,
  earb   = ending_ar,
  dart   = 39,
  period = "quarter"
) |> 
  gt(rowname_col = "nqtr") |> 
  cols_hide(c(date, 
              nmon, 
              month,
              ndip,
              ending_ar_target,
              dar_diff,
              ratio_ideal,
              ratio_actual)) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  fmt_currency(columns = c(gross_charges, 
                           ending_ar, 
                           adc, 
                           ending_ar_target, 
                           ending_ar_dec_abs, 
                           earb_gct_diff)) |> 
  # fmt_tf(columns = c(dar_pass), tf_style = "check-mark") |> 
  fmt_percent(columns = c(ending_ar_dec_pct)) |> 
  fmt_number(columns = c(dar, 
                         dar_diff, 
                         ratio_actual, 
                         ratio_ideal, 
                         ratio_diff)) |> 
  cols_move_to_start(c(nqtr, 
                       gross_charges, 
                       ending_ar, 
                       earb_gct_diff,
                       adc, 
                       dar_pass, 
                       dar, 
                       dar_diff, 
                       ratio_actual, 
                       ratio_ideal, 
                       ratio_diff, 
                       ending_ar_target, 
                       ending_ar_dec_abs, 
                       ending_ar_dec_pct
                       )) |> 
  cols_label(
    gross_charges = "Gross Charges",
    ending_ar = "Ending AR",
    adc = "ADC",
    dar_pass = "",
    dar = "DAR",
    ratio_diff = "AR/GC Diff",
    ending_ar_dec_abs = "AR Decrease Needed",
    ending_ar_dec_pct = "%",
    earb_gct_diff = "AR - GC"
  ) |> 
  opt_stylize()
```

## Aging Bins

```{r}
binned <- bin_aging(
  df = load_ex("aging_ex"),
  date = dos
  ) |>
  dplyr::select(
    dos:ins_class,
    dar:aging_bin
    )

binned
```

```{r}
binned |> 
  sorted_bars(ins_name) +
  theme_minimal()
```


```{r}
binned |>
  arrange(aging_bin) |>
  summarise(n_claims = n(),
            balance = sum(charges),
            .by = aging_bin) |>
  mutate(pct_claims = n_claims / sum(n_claims),
         pct_balance = balance / sum(balance)) |>
  gt(rowname_col = "aging_bin") |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  fmt_percent(columns = pct_claims:pct_balance, decimals = 0) |>
  fmt_currency(columns = balance, decimals = 0) |>
  fmt_number(columns = n_claims, decimals = 0) |>
  opt_stylize() |>
  cols_label(n_claims = "Claims", balance = "Charges") |>
  cols_move_to_start(c(n_claims, pct_claims, balance, pct_balance)) |>
  cols_merge(c(n_claims, pct_claims), pattern = "{1} ({2})") |>
  cols_merge(c(balance, pct_balance), pattern = "{1} ({2})") |>
  tab_header(title = "Aging Report", ) |>
  tab_options(heading.align = "left",
              quarto.disable_processing = TRUE)
```


```{r}
binned |>
  arrange(aging_bin, ins_name) |>
  summarise(
    n_claims = n(),
    balance = sum(charges),
    .by = c(aging_bin, ins_name)
  ) |>
  mutate(pct_claims = n_claims / sum(n_claims),
         pct_balance = balance / sum(balance)) |>
  gt(groupname_col = "aging_bin", rowname_col = "ins_name") |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  fmt_percent(columns = pct_claims:pct_balance) |>
  fmt_currency(columns = balance, decimals = 0) |>
  fmt_number(columns = n_claims, decimals = 0) |>
  cols_label(n_claims = "Claims", balance = "Charges") |>
  cols_merge(c(n_claims, pct_claims), pattern = "{1} ({2})") |>
  cols_merge(c(balance, pct_balance), pattern = "{1} ({2})") |>
  opt_stylize()
```


```{r}
binned |>
  arrange(ins_name, aging_bin) |>
  summarise(
    n_claims = n(),
    balance = sum(charges),
    .by = c(aging_bin, ins_name)
  ) |>
  mutate(pct_claims = n_claims / sum(n_claims),
                pct_balance = balance / sum(balance),
                .by = ins_name) |>
  gt(groupname_col = "aging_bin", rowname_col = "ins_name") |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  fmt_percent(columns = pct_claims:pct_balance) |> 
  fmt_currency(columns = balance) |> 
  fmt_number(columns = n_claims, decimals = 0) |> 
  cols_label(n_claims = "Claims", balance = "Charges") |>
  cols_merge(c(n_claims, pct_claims), pattern = "{1} ({2})") |>
  cols_merge(c(balance, pct_balance), pattern = "{1} ({2})") |>
  opt_stylize()
```
