---
title: "Tests"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%"
)
options(scipen = 999)

library(forager)
library(dplyr)
library(lubridate)
library(clock)
library(tidyr)
library(ggplot2)
# library(ggforce)
library(scales)
library(ggthemes)
library(gt)
```





## Aging Over 3 Months

```{r}
load_ex("old_azalea") |> 
  select(-starts_with("bin")) |> 
  mutate(rep_mon = factor(rep_mon, levels = month.abb, ordered = TRUE),
         aging_bin = factor(aging_bin, levels = sort(unique(aging_bin)), ordered = TRUE)) |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r eval=FALSE, echo=FALSE}
old <- load_ex("old_azalea") |> 
  select(-starts_with("bin")) |> 
  mutate(rep_mon = factor(rep_mon, levels = month.abb, ordered = TRUE))
  # ggplot(aes(x = rep_date, y = balance, group = pid, fill = aging_bin)) +
  ggplot() +
  # geom_point(aes(x = rep_date, y = balance, colour = rep_mon)) + 
  geom_point(aes(x = dos, y = balance, fill = rep_mon, colour = aging_bin)) + 
  geom_pointrange(aes(x = rep_date, y = balance, xmin = dos, xmax = rep_date, colour = rep_mon)) +
  ggthemes::geom_rangeframe() +
  ggthemes::theme_pander() +
  labs(x = "", y = "") + 
  geom_point(aes(x = start_date, y = apartment)) +
  geom_point(aes(fill = aging_bin), shape = 21, size = 4) +
  geom_line(colour = "grey") +
```

```{r eval=FALSE, echo=FALSE}
ggplot(old, aes(y = aging_bin, x = balance)) +
  geom_boxplot(aes(fill = ins_name), width = .4) +
  theme(legend.position = "none") +
  labs(x = NULL, y = NULL)
  geom_line(aes(group = rep_mon), colour = "#3366FF", alpha = 0.5) +
  geom_point(aes(fill = aging_bin, group = ins_name, size = days_in_ar), shape = 21, stroke = 1) +
  scale_x_date(date_breaks = "month", date_minor_breaks = "day", date_labels = "%b %d") +
  scale_shape_identity() +
  ggthemes::scale_color_fivethirtyeight() +
  ggthemes::theme_fivethirtyeight(base_size = 10)
```



```{r}
biweekly <- load_ex("aging_biweekly") |>
  mutate(year = get_year(date), 
         month = date_month_factor(date, abbreviate = TRUE), 
         .after = date) |> 
  arrange(date, aging_bin)

ggplot(data = biweekly, 
       aes(x = forcats::fct_rev(aging_bin), y = balance, fill = date)) +
  geom_col(position = position_stack(reverse = TRUE)) +
  # geom_col(position = position_fill(reverse = TRUE)) +
  coord_flip(clip = "off") +
  labs(title = NULL, x = NULL) + 
  ggthemes::scale_color_fivethirtyeight() +
  ggthemes::theme_fivethirtyeight(base_size = 10) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 12, face = "bold")
        )
```





```{r}
agingex <- load_ex("aging_ex")[1:4] |> 
  days_between(dos) |> 
  bin_aging(days_elapsed) |>
  mutate(year = get_year(dos), 
         quarter = get_quarter(as_year_quarter_day(dos)),
         month = date_month_factor(dos), 
         .after = dos)

agingex |>
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("aging_facility") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("aging_monthly") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("cppm_ex") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("healthyr") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("monthly_raw") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```





```{r}
load_ex("denials_extract") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("nm_examples")$collections |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("nm_examples")$em_visits |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("nm_examples")$reimbursement |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("nm_examples")$last_referral |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```






```{r}
load_ex("patient_aging") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


```{r}
load_ex("transaction_data") |> 
  gt::gt_preview() |> 
  opt_table_font(font = google_font(name = "Fira Code"))
```


