# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <sorted_bars>
  ":=",
  # <avg_dar>
  "adc",
  # <mock_claims>
  "age",
  # <bin_aging>
  # <mock_parbx>
  "aging_bin",
  # <mock_claims>
  "balance",
  # <mock_claims>
  "charges",
  # <mock_claims>
  "date_acceptance",
  # <mock_claims>
  "date_adjudication",
  # <mock_claims>
  "date_reconciliation",
  # <mock_claims>
  "date_release",
  # <mock_claims>
  "date_service",
  # <mock_claims>
  "date_submission",
  # <predict_net>
  "earb_gt120",
  # <predict_net>
  "earb_lt120",
  # <avg_dar>
  "earb_target",
  # <net_ex>
  "ending_ar",
  # <net_ex>
  "gross_charges",
  # <parbx_ex_>
  "month",
  # <avg_dar>
  "ndip",
  # <predict_net>
  "net_diff",
  # <net_ex>
  "net_payment",
  # <predict_net>
  "net_pred",
  # <predict_net>
  "parl_120",
  # <predict_net>
  "pct_paid",
  # <avg_dar>
  "ratio_actual",
  # <avg_dar>
  "ratio_ideal",
  NULL
))
