# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <avg_dar>
  "adc",
  # <bin_aging>
  # <prep_claims>
  "aging_bin",
  # <mock_claims>
  # <prep_claims>
  # <summarise_claims>
  "balance",
  # <mock_parbx>
  "bin",
  # <mock_claims>
  # <prep_claims>
  # <summarise_claims>
  "charges",
  # <prep_claims>
  # <summarise_claims>
  "dar",
  # <mock_claims>
  # <prep_claims>
  "date_acc",
  # <mock_claims>
  # <prep_claims>
  "date_adj",
  # <mock_claims>
  # <prep_claims>
  "date_rec",
  # <mock_claims>
  # <prep_claims>
  "date_rel",
  # <mock_claims>
  # <prep_claims>
  "date_srv",
  # <mock_claims>
  # <prep_claims>
  "date_sub",
  # <prep_claims>
  "dates",
  # <prep_claims>
  "days",
  # <prep_claims>
  "days_srv",
  # <prep_claims>
  "dtype",
  # <predict_net>
  "earb_gt120",
  # <predict_net>
  "earb_lt120",
  # <avg_dar>
  "earb_target",
  # <net_ex>
  "ending_ar",
  # <net_ex>
  "gross_charges",
  # <prep_claims>
  "id",
  # <mock_parbx>
  "month",
  # <avg_dar>
  "ndip",
  # <predict_net>
  "net_diff",
  # <net_ex>
  "net_payment",
  # <predict_net>
  "net_pred",
  # <predict_net>
  "parl_120",
  # <prep_claims>
  "payer",
  # <predict_net>
  "pct_paid",
  # <avg_dar>
  "ratio_actual",
  # <avg_dar>
  "ratio_ideal",
  NULL
))
