# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <avg_dar>
  # <count_days>
  # <age_days>
  ":=",
  # <avg_dar>
  "adc",
  # <bin_aging>
  # <avg_dar>
  "dar",
  # <generate_data>
  "date_of_acceptance",
  # <generate_data>
  "date_of_release",
  # <generate_data>
  "date_of_service",
  # <generate_data>
  "date_of_submission",
  # <avg_dar>
  "max_nmon",
  # <avg_dar>
  "month",
  # <avg_dar>
  "ndip",
  # <avg_dar>
  "nmon",
  # <avg_dar>
  "nqtr",
  # <avg_dar>
  "ratio_actual",
  # <avg_dar>
  "ratio_ideal",
  NULL
))
