# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  ":=", # <age_days>
  "ndip", # <dar_month>
  "adc", # <dar_month>
  "actual", # <dar_month>
  "ideal", # <dar_month>
  "earb_trg", # <dar_month>
  "earb_dc", # <dar_month>
  "month", # <dar_month>
  "nmon", # <dar_month>
  "earb_pct", # <dar_month>
  "dar", # <dar_month>
  "pass", # <dar_month>
  "radiff", # <dar_month>
  "nmon", # <dar_qtr>
  "nqtr", # <dar_qtr>
  "ndip", # <dar_qtr>
  "gct_qtr", # <dar_qtr>
  "adc", # <dar_qtr>
  "actual", # <dar_qtr>
  "ideal", # <dar_qtr>
  "earb_trg", # <dar_qtr>
  "earb_dc", # <dar_qtr>
  "earb_pct", # <dar_qtr>
  "dar", # <dar_qtr>
  "pass", # <dar_qtr>
  "radiff", # <dar_qtr>
  NULL
))
