#' Prep mock coding/billing data frame
#'
#' @param df `[data.frame]` data frame generated by `mock_claims()`
#' @param ... `[dots]` additional arguments
#' @returns A [tibble][tibble::tibble-package]
#' @examples
#' prep_claims(mock_claims(500))
#' @autoglobal
#' @export
prep_claims <- function(df, ...) {
  df |>
    tidyr::pivot_longer(
      cols = dplyr::starts_with("date"),
      names_to = "dtype",
      names_prefix = "date_",
      values_to = "date"
    ) |>
    dplyr::mutate(
      dtype = forcats::fct_relevel(
        dtype,
        "srv",
        "rel",
        "sub",
        "acc",
        "adj",
        "rec"
      ),
      days = as.integer(dplyr::lead(date) - date),
      days = dplyr::lag(days, order_by = date),
      .by = id
    ) |>
    dplyr::arrange(id, dtype) |>
    tidyr::pivot_wider(
      names_from = dtype,
      names_glue = "{.value}_{dtype}",
      values_from = c(date, days)
    ) |>
    dplyr::rowwise() |>
    dplyr::mutate(
      dar = dplyr::if_else(
        !is.na(date_rec),
        as.integer(date_rec - date_srv),
        as.integer(date_adj - date_srv)
      )
    ) |>
    dplyr::ungroup() |>
    tidyr::nest(
      dates = c(
        date_rel,
        date_sub,
        date_acc,
        date_adj,
        date_rec
      )
    ) |>
    bin_aging(dar) |>
    dplyr::select(
      id,
      payer,
      charges,
      balance,
      date_srv,
      aging_bin,
      dar,
      dplyr::starts_with("days_"),
      dates
    ) |>
    dplyr::select(-days_srv) |>
    .add_class()
}

#' Summarise mock coding/billing data frame
#'
#' @param df `[data.frame]` data generated from `prep_claims(mock_claims())`
#' @param vars `[character]` variables to summarise, e.g. `c(days_srv, days_rec)`
#' @returns A [tibble][tibble::tibble-package]
#' @examples
#' x <- mock_claims(5000)
#' x
#'
#' x <- prep_claims(x)
#' x
#'
#' summarise_claims(x) |>
#' dplyr::glimpse()
#'
#' dplyr::group_by(x,
#' year = ymd::year(date_srv),
#' month = ymd::month(date_srv)) |>
#' summarise_claims() |>
#' dplyr::glimpse()
#' @autoglobal
#' @export
summarise_claims <- function(df, vars = c(dplyr::starts_with("days_"), dar)) {
  dplyr::summarise(
    df,
    n_claims = dplyr::n(),
    gross_charges = sum(charges, na.rm = TRUE),
    ending_ar = sum(balance, na.rm = TRUE),
    dplyr::across({{ vars }}, \(x) mean(x), .names = "mean_{.col}"),
    .groups = "drop"
  ) |>
    dplyr::rename_with(
      ~ stringr::str_replace(.x, "days_", ""),
      dplyr::starts_with("mean_")
    ) |>
    .add_class()
}
