#' Prep mock coding/billing data frame
#'
#' @param df `[data.frame]` data frame generated by `mock_claims()`
#'
#' @param ... `[dots]` additional arguments
#'
#' @returns A [tibble][tibble::tibble-package]
#'
#' @examples
#' prep_claims(mock_claims(rows = 5))
#'
#' @autoglobal
#'
#' @export
prep_claims <- function(df, ...) {

  df |>
    tidyr::pivot_longer(
      cols         = dplyr::starts_with("date"),
      names_to     = "date_type",
      names_prefix = "date_",
      values_to    = "date") |>
    dplyr::mutate(
      date_type = forcats::fct_relevel(
        date_type,
        "service",
        "release",
        "submission",
        "acceptance",
        "adjudication",
        "reconciliation"),
      days = as.numeric(dplyr::lead(date) - date),
      days = dplyr::lag(days, order_by = date),
      .by = claimid) |>
    dplyr::arrange(claimid, date_type) |>
    tidyr::pivot_wider(
      names_from = date_type,
      names_glue = "{.value}_{date_type}",
      values_from = c(date, days)
    ) |>
    remove_quiet() |>
    dplyr::rowwise() |>
    dplyr::mutate(dar = dplyr::if_else(
      !is.na(date_reconciliation),
      as.numeric(date_reconciliation - date_service),
      as.numeric(date_adjudication - date_service)
    )) |>
    dplyr::ungroup() |>
    tidyr::nest(
      dates = c(
        date_release,
        date_submission,
        date_acceptance,
        date_adjudication,
        date_reconciliation)
    ) |>
    bin_aging(dar) |>
    dplyr::select(
      claimid,
      payer,
      charges,
      balance,
      date_service,
      aging_bin,
      dar,
      dplyr::starts_with("days_"),
      dates
    ) |>
    .add_class()
}

#' Summarise mock coding/billing data frame
#'
#' @param df `[data.frame]` data frame generated from `mock_claims() |> prep_claims()`
#'
#' @param vars `[character]` variables to summarise, e.g. `c(days_service, days_reconciliation)`
#'
#' @returns A [tibble][tibble::tibble-package]
#'
#' @examples
#' x <- mock_claims(rows = 500) |> prep_claims()
#'
#' summarise_claims(x)
#'
#' x |>
#'   dplyr::group_by(
#'     year = ymd::year(date_service),
#'     month = ymd::month(date_service)) |>
#'   summarise_claims()
#'
#' @autoglobal
#'
#' @export
summarise_claims <- function(df, vars = c(dplyr::starts_with("days_"), dar)) {

  df |>
    dplyr::summarise(
      n_claims      = dplyr::n(),
      gross_charges = sum_na(charges),
      ending_ar     = sum_na(balance),
      dplyr::across({{ vars }}, \(x) mean_na(x), .names = "mean_{.col}"),
      .groups = "drop"
    ) |>
    dplyr::rename_with(
      ~ stringr::str_replace(.x, "days_", ""),
      dplyr::starts_with("mean_")
    ) |>
    .add_class()

}
